// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Servidor_Sistema_Geologia.DAL;

#nullable disable

namespace Servidor_Sistema_Geologia.Migrations
{
    [DbContext(typeof(GestorSistemaGeologia))]
    [Migration("20250419161307_UpdateSubType")]
    partial class UpdateSubType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Servidor_Sistema_Geologia.Models.Acceso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ElementoGeologicoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaAcceso")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ElementoGeologicoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Accesos");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Models.ElementoGeologico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DocumentosRelacionados")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Donante")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Edad")
                        .HasColumnType("decimal(20,0)");

                    b.Property<long?>("Ejemplares")
                        .HasColumnType("bigint");

                    b.Property<int?>("EstadoElementoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GaleriaElementosGeologicoId")
                        .HasColumnType("int");

                    b.Property<bool?>("LaminaExiste")
                        .HasColumnType("bit");

                    b.Property<string>("LaminaURL")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TipoElemento")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<int?>("UbicacionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstadoElementoId");

                    b.HasIndex("GaleriaElementosGeologicoId")
                        .IsUnique()
                        .HasFilter("[GaleriaElementosGeologicoId] IS NOT NULL");

                    b.HasIndex("UbicacionId");

                    b.ToTable("ElementosGeologicos");

                    b.HasDiscriminator<string>("TipoElemento").HasValue("ElementoGeologico");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Models.EstadoElemento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DescripcionEstado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EstadosElementos");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Models.FotoElemento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DescripcionEspecifica")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Etiquetas")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("FechaSubida")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GaleriaElementosGeologicoId")
                        .HasColumnType("int");

                    b.Property<byte[]>("Imagen")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("TipoFoto")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("GaleriaElementosGeologicoId");

                    b.ToTable("FotosElementos");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Models.GaleriaElementoGeologico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DetalleGrupo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ElementoGeologicoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("GaleriaElementosGeologicos");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Models.Pais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NombrePais")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Paises");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Models.Provincia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreProvincia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PaisId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaisId");

                    b.ToTable("Provincias");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Models.Ubicacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Latitud")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Leyenda")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Localidad")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Longitud")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int?>("PaisId")
                        .HasColumnType("int");

                    b.Property<int?>("ProvinciaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaisId");

                    b.HasIndex("ProvinciaId");

                    b.ToTable("Ubicaciones");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreCompleto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Models.Fosil", b =>
                {
                    b.HasBaseType("Servidor_Sistema_Geologia.Models.ElementoGeologico");

                    b.Property<string>("Especie")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Periodo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TipoFosil")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Fosil");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Models.Mineral", b =>
                {
                    b.HasBaseType("Servidor_Sistema_Geologia.Models.ElementoGeologico");

                    b.Property<string>("Litologia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TipoMineral")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasDiscriminator().HasValue("Mineral");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Models.Roca", b =>
                {
                    b.HasBaseType("Servidor_Sistema_Geologia.Models.ElementoGeologico");

                    b.Property<string>("Litologia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TipoRoca")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.ToTable("ElementosGeologicos", t =>
                        {
                            t.Property("Litologia")
                                .HasColumnName("Roca_Litologia");
                        });

                    b.HasDiscriminator().HasValue("Roca");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Models.Acceso", b =>
                {
                    b.HasOne("Servidor_Sistema_Geologia.Models.ElementoGeologico", "ElementoGeologico")
                        .WithMany()
                        .HasForeignKey("ElementoGeologicoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Servidor_Sistema_Geologia.Models.Usuario", "Usuario")
                        .WithMany("Accesos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ElementoGeologico");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Models.ElementoGeologico", b =>
                {
                    b.HasOne("Servidor_Sistema_Geologia.Models.EstadoElemento", "EstadoElemento")
                        .WithMany()
                        .HasForeignKey("EstadoElementoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Servidor_Sistema_Geologia.Models.GaleriaElementoGeologico", "Galeria")
                        .WithOne("ElementoGeologico")
                        .HasForeignKey("Servidor_Sistema_Geologia.Models.ElementoGeologico", "GaleriaElementosGeologicoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Servidor_Sistema_Geologia.Models.Ubicacion", "Ubicacion")
                        .WithMany("ElementosGeologicos")
                        .HasForeignKey("UbicacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("EstadoElemento");

                    b.Navigation("Galeria");

                    b.Navigation("Ubicacion");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Models.FotoElemento", b =>
                {
                    b.HasOne("Servidor_Sistema_Geologia.Models.GaleriaElementoGeologico", "Galeria")
                        .WithMany("Fotos")
                        .HasForeignKey("GaleriaElementosGeologicoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Galeria");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Models.Provincia", b =>
                {
                    b.HasOne("Servidor_Sistema_Geologia.Models.Pais", "Pais")
                        .WithMany("Provincias")
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Models.Ubicacion", b =>
                {
                    b.HasOne("Servidor_Sistema_Geologia.Models.Pais", "Pais")
                        .WithMany("Ubicaciones")
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Servidor_Sistema_Geologia.Models.Provincia", "Provincia")
                        .WithMany("Ubicaciones")
                        .HasForeignKey("ProvinciaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Pais");

                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Models.GaleriaElementoGeologico", b =>
                {
                    b.Navigation("ElementoGeologico");

                    b.Navigation("Fotos");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Models.Pais", b =>
                {
                    b.Navigation("Provincias");

                    b.Navigation("Ubicaciones");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Models.Provincia", b =>
                {
                    b.Navigation("Ubicaciones");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Models.Ubicacion", b =>
                {
                    b.Navigation("ElementosGeologicos");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Models.Usuario", b =>
                {
                    b.Navigation("Accesos");
                });
#pragma warning restore 612, 618
        }
    }
}
