// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Servidor_Sistema_Geologia.DAL;

#nullable disable

namespace Servidor_Sistema_Geologia.Migrations
{
    [DbContext(typeof(GestorGeologia))]
    [Migration("20250116224612_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Servidor_Sistema_Geologia.Models.Acceso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Accion")
                        .HasColumnType("int");

                    b.Property<int?>("ElementoGeologicoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAcceso")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ElementoGeologicoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Accesos");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Models.ElementoGeologico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("DocumentosRelacionados")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Donante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Edad")
                        .HasColumnType("int");

                    b.Property<int?>("Ejemplares")
                        .HasColumnType("int");

                    b.Property<int?>("EstadoElementoId")
                        .HasColumnType("int");

                    b.Property<int>("FechaIngreso")
                        .HasColumnType("int");

                    b.Property<bool?>("LaminaExiste")
                        .HasColumnType("bit");

                    b.Property<string>("LaminaURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UbicacionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstadoElementoId");

                    b.HasIndex("UbicacionId");

                    b.ToTable("ElementosGeologicos");

                    b.HasDiscriminator().HasValue("ElementoGeologico");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Models.EstadoElemento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DescripcionEstado")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EstadosElementos");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Models.FotoElemento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreadoPor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescripcionEspecifica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ElementoGeologicoId")
                        .HasColumnType("int");

                    b.Property<string>("Etiquetas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaSubida")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GaleriaElementosGeologicoId")
                        .HasColumnType("int");

                    b.Property<int?>("GaleriaId")
                        .HasColumnType("int");

                    b.Property<byte[]>("Imagen")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("TipoFoto")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ElementoGeologicoId");

                    b.HasIndex("GaleriaId");

                    b.ToTable("FotosElementos");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Models.GaleriaElementoGeologico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DetalleGrupo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ElementoGeologicoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ElementoGeologicoId");

                    b.ToTable("GaleriaElementosGeologicos");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Models.Pais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NombrePais")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Paises");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Models.Provincia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreProvincia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PaisId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaisId");

                    b.ToTable("Provincias");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Models.Ubicacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Latitud")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Leyenda")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Localidad")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Longitud")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int?>("PaisId")
                        .HasColumnType("int");

                    b.Property<int?>("ProvinciaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaisId");

                    b.HasIndex("ProvinciaId");

                    b.ToTable("Ubicaciones");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Models.Fosil", b =>
                {
                    b.HasBaseType("Servidor_Sistema_Geologia.Models.ElementoGeologico");

                    b.Property<string>("Especie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Periodo")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Fosil");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Models.Roca", b =>
                {
                    b.HasBaseType("Servidor_Sistema_Geologia.Models.ElementoGeologico");

                    b.Property<string>("Litologia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoRoca")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Roca");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Models.Acceso", b =>
                {
                    b.HasOne("Servidor_Sistema_Geologia.Models.ElementoGeologico", "ElementoGeologico")
                        .WithMany()
                        .HasForeignKey("ElementoGeologicoId");

                    b.HasOne("Servidor_Sistema_Geologia.Models.Usuario", "Usuario")
                        .WithMany("Accesos")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("ElementoGeologico");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Models.ElementoGeologico", b =>
                {
                    b.HasOne("Servidor_Sistema_Geologia.Models.EstadoElemento", "EstadoElemento")
                        .WithMany()
                        .HasForeignKey("EstadoElementoId");

                    b.HasOne("Servidor_Sistema_Geologia.Models.Ubicacion", "Ubicacion")
                        .WithMany("ElementosGeologicos")
                        .HasForeignKey("UbicacionId");

                    b.Navigation("EstadoElemento");

                    b.Navigation("Ubicacion");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Models.FotoElemento", b =>
                {
                    b.HasOne("Servidor_Sistema_Geologia.Models.ElementoGeologico", "ElementoGeologico")
                        .WithMany("Fotos")
                        .HasForeignKey("ElementoGeologicoId");

                    b.HasOne("Servidor_Sistema_Geologia.Models.GaleriaElementoGeologico", "Galeria")
                        .WithMany("Fotos")
                        .HasForeignKey("GaleriaId");

                    b.Navigation("ElementoGeologico");

                    b.Navigation("Galeria");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Models.GaleriaElementoGeologico", b =>
                {
                    b.HasOne("Servidor_Sistema_Geologia.Models.ElementoGeologico", "ElementoGeologico")
                        .WithMany()
                        .HasForeignKey("ElementoGeologicoId");

                    b.Navigation("ElementoGeologico");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Models.Provincia", b =>
                {
                    b.HasOne("Servidor_Sistema_Geologia.Models.Pais", "Pais")
                        .WithMany("Provincias")
                        .HasForeignKey("PaisId");

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Models.Ubicacion", b =>
                {
                    b.HasOne("Servidor_Sistema_Geologia.Models.Pais", "Pais")
                        .WithMany()
                        .HasForeignKey("PaisId");

                    b.HasOne("Servidor_Sistema_Geologia.Models.Provincia", "Provincia")
                        .WithMany("Ubicaciones")
                        .HasForeignKey("ProvinciaId");

                    b.Navigation("Pais");

                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Models.ElementoGeologico", b =>
                {
                    b.Navigation("Fotos");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Models.GaleriaElementoGeologico", b =>
                {
                    b.Navigation("Fotos");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Models.Pais", b =>
                {
                    b.Navigation("Provincias");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Models.Provincia", b =>
                {
                    b.Navigation("Ubicaciones");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Models.Ubicacion", b =>
                {
                    b.Navigation("ElementosGeologicos");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Models.Usuario", b =>
                {
                    b.Navigation("Accesos");
                });
#pragma warning restore 612, 618
        }
    }
}
