// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Servidor_Sistema_Geologia;

#nullable disable

namespace Servidor_Sistema_Geologia.Migrations
{
    [DbContext(typeof(SistemaGeologicoDbContext))]
    [Migration("20260224125734_RenombrarTablasColumnasCamelCase")]
    partial class RenombrarTablasColumnasCamelCase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RolClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UsuarioClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UsuarioLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UsuarioRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UsuarioTokens", (string)null);
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.ElementoGeologico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("codigo");

                    b.Property<string>("DocumentosRelacionados")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("documentosRelacionados");

                    b.Property<string>("Donante")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("donante");

                    b.Property<string>("Edad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("edad");

                    b.Property<long>("Ejemplares")
                        .HasColumnType("bigint")
                        .HasColumnName("ejemplares");

                    b.Property<bool>("EstadoActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("estadoActivo");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaActualizacion");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaCreacion")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaEliminacion");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaIngreso");

                    b.Property<bool>("LaminaExiste")
                        .HasColumnType("bit")
                        .HasColumnName("laminaExiste");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nombre");

                    b.Property<int?>("UbicacionId")
                        .HasColumnType("int")
                        .HasColumnName("ubicacionId");

                    b.Property<int?>("UsuarioActualizacionId")
                        .HasColumnType("int")
                        .HasColumnName("usuarioActualizacionId");

                    b.Property<int?>("UsuarioCreacionId")
                        .HasColumnType("int")
                        .HasColumnName("usuarioCreacionId");

                    b.Property<int?>("UsuarioEliminacionId")
                        .HasColumnType("int")
                        .HasColumnName("usuarioEliminacionId");

                    b.Property<string>("tipoElemento")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("IX_ElementosGeologicos_Codigo");

                    b.HasIndex("UbicacionId");

                    b.HasIndex("UsuarioActualizacionId");

                    b.HasIndex("UsuarioCreacionId");

                    b.HasIndex("UsuarioEliminacionId");

                    b.ToTable("tb_ElementosGeologicos", (string)null);

                    b.HasDiscriminator<string>("tipoElemento").HasValue("ElementoGeologico");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Galeria.FotoElemento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DescripcionEspecifica")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("descripcionEspecifica");

                    b.Property<bool>("EstadoActivo")
                        .HasColumnType("bit")
                        .HasColumnName("estadoActivo");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaActualizacion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaCreacion");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaEliminacion");

                    b.Property<int>("GaleriaElementosGeologicoId")
                        .HasColumnType("int")
                        .HasColumnName("galeriaElementosGeologicoId");

                    b.Property<byte[]>("Imagen")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("imagen");

                    b.Property<int>("TipoFoto")
                        .HasColumnType("int")
                        .HasColumnName("tipoFoto");

                    b.Property<int?>("UsuarioActualizacionId")
                        .HasColumnType("int")
                        .HasColumnName("usuarioActualizacionId");

                    b.Property<int?>("UsuarioCreacionId")
                        .HasColumnType("int")
                        .HasColumnName("usuarioCreacionId");

                    b.Property<int?>("UsuarioEliminacionId")
                        .HasColumnType("int")
                        .HasColumnName("usuarioEliminacionId");

                    b.HasKey("Id");

                    b.HasIndex("GaleriaElementosGeologicoId");

                    b.HasIndex("UsuarioActualizacionId");

                    b.HasIndex("UsuarioCreacionId");

                    b.HasIndex("UsuarioEliminacionId");

                    b.ToTable("tb_FotosElementos", (string)null);
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Galeria.GaleriaElementoGeologico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DetalleGrupo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("detalleGrupo");

                    b.Property<int>("ElementoGeologicoId")
                        .HasColumnType("int")
                        .HasColumnName("elementoGeologicoId");

                    b.Property<bool>("EstadoActivo")
                        .HasColumnType("bit")
                        .HasColumnName("estadoActivo");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaActualizacion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaCreacion");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaEliminacion");

                    b.Property<int?>("UsuarioActualizacionId")
                        .HasColumnType("int")
                        .HasColumnName("usuarioActualizacionId");

                    b.Property<int?>("UsuarioCreacionId")
                        .HasColumnType("int")
                        .HasColumnName("usuarioCreacionId");

                    b.Property<int?>("UsuarioEliminacionId")
                        .HasColumnType("int")
                        .HasColumnName("usuarioEliminacionId");

                    b.HasKey("Id");

                    b.HasIndex("ElementoGeologicoId")
                        .IsUnique();

                    b.HasIndex("UsuarioActualizacionId");

                    b.HasIndex("UsuarioCreacionId");

                    b.HasIndex("UsuarioEliminacionId");

                    b.ToTable("tb_GaleriaElementosGeologicos", (string)null);
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Pais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EstadoActivo")
                        .HasColumnType("bit")
                        .HasColumnName("estadoActivo");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaActualizacion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaCreacion");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaEliminacion");

                    b.Property<string>("NombrePais")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombrePais");

                    b.Property<int?>("UsuarioActualizacionId")
                        .HasColumnType("int")
                        .HasColumnName("usuarioActualizacionId");

                    b.Property<int?>("UsuarioCreacionId")
                        .HasColumnType("int")
                        .HasColumnName("usuarioCreacionId");

                    b.Property<int?>("UsuarioEliminacionId")
                        .HasColumnType("int")
                        .HasColumnName("usuarioEliminacionId");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioActualizacionId");

                    b.HasIndex("UsuarioCreacionId");

                    b.HasIndex("UsuarioEliminacionId");

                    b.ToTable("tb_Paises", (string)null);
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Provincia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EstadoActivo")
                        .HasColumnType("bit")
                        .HasColumnName("estadoActivo");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaActualizacion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaCreacion");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaEliminacion");

                    b.Property<string>("NombreProvincia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombreProvincia");

                    b.Property<int>("PaisId")
                        .HasColumnType("int")
                        .HasColumnName("paisId");

                    b.Property<int?>("UsuarioActualizacionId")
                        .HasColumnType("int")
                        .HasColumnName("usuarioActualizacionId");

                    b.Property<int?>("UsuarioCreacionId")
                        .HasColumnType("int")
                        .HasColumnName("usuarioCreacionId");

                    b.Property<int?>("UsuarioEliminacionId")
                        .HasColumnType("int")
                        .HasColumnName("usuarioEliminacionId");

                    b.HasKey("Id");

                    b.HasIndex("PaisId");

                    b.HasIndex("UsuarioActualizacionId");

                    b.HasIndex("UsuarioCreacionId");

                    b.HasIndex("UsuarioEliminacionId");

                    b.ToTable("tb_Provincias", (string)null);
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Ubicacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EstadoActivo")
                        .HasColumnType("bit")
                        .HasColumnName("estadoActivo");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaActualizacion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaCreacion");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaEliminacion");

                    b.Property<string>("Latitud")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("latitud");

                    b.Property<string>("Leyenda")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("leyenda");

                    b.Property<string>("Localidad")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("localidad");

                    b.Property<string>("Longitud")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("longitud");

                    b.Property<int>("PaisId")
                        .HasColumnType("int")
                        .HasColumnName("paisId");

                    b.Property<int>("ProvinciaId")
                        .HasColumnType("int")
                        .HasColumnName("provinciaId");

                    b.Property<int?>("UsuarioActualizacionId")
                        .HasColumnType("int")
                        .HasColumnName("usuarioActualizacionId");

                    b.Property<int?>("UsuarioCreacionId")
                        .HasColumnType("int")
                        .HasColumnName("usuarioCreacionId");

                    b.Property<int?>("UsuarioEliminacionId")
                        .HasColumnType("int")
                        .HasColumnName("usuarioEliminacionId");

                    b.HasKey("Id");

                    b.HasIndex("PaisId");

                    b.HasIndex("ProvinciaId");

                    b.HasIndex("UsuarioActualizacionId");

                    b.HasIndex("UsuarioCreacionId");

                    b.HasIndex("UsuarioEliminacionId");

                    b.ToTable("tb_Ubicaciones", (string)null);
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("EstadoActivo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NombreCompleto")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("Rol")
                        .HasColumnType("int")
                        .HasColumnName("Rol");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Usuarios_Email")
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Fosil", b =>
                {
                    b.HasBaseType("Servidor_Sistema_Geologia.ElementoGeologico");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("especie");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("periodo");

                    b.Property<int>("TipoFosil")
                        .HasColumnType("int")
                        .HasColumnName("tipoFosil");

                    b.HasDiscriminator().HasValue("Fosil");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Mineral", b =>
                {
                    b.HasBaseType("Servidor_Sistema_Geologia.ElementoGeologico");

                    b.Property<string>("Litologia")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("litologia");

                    b.Property<int>("TipoMineral")
                        .HasColumnType("int")
                        .HasColumnName("tipoMineral");

                    b.HasDiscriminator().HasValue("Mineral");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Roca", b =>
                {
                    b.HasBaseType("Servidor_Sistema_Geologia.ElementoGeologico");

                    b.Property<string>("Litologia")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("litologia_roca");

                    b.Property<int>("TipoRoca")
                        .HasColumnType("int")
                        .HasColumnName("tipoRoca");

                    b.HasDiscriminator().HasValue("Roca");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Servidor_Sistema_Geologia.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Servidor_Sistema_Geologia.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Servidor_Sistema_Geologia.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Servidor_Sistema_Geologia.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.ElementoGeologico", b =>
                {
                    b.HasOne("Servidor_Sistema_Geologia.Ubicacion", "Ubicacion")
                        .WithMany("ElementosGeologicos")
                        .HasForeignKey("UbicacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Servidor_Sistema_Geologia.Usuario", "UsuarioActualizacion")
                        .WithMany()
                        .HasForeignKey("UsuarioActualizacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Servidor_Sistema_Geologia.Usuario", "UsuarioCreacion")
                        .WithMany()
                        .HasForeignKey("UsuarioCreacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Servidor_Sistema_Geologia.Usuario", "UsuarioEliminacion")
                        .WithMany()
                        .HasForeignKey("UsuarioEliminacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Ubicacion");

                    b.Navigation("UsuarioActualizacion");

                    b.Navigation("UsuarioCreacion");

                    b.Navigation("UsuarioEliminacion");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Galeria.FotoElemento", b =>
                {
                    b.HasOne("Servidor_Sistema_Geologia.Galeria.GaleriaElementoGeologico", "Galeria")
                        .WithMany("Fotos")
                        .HasForeignKey("GaleriaElementosGeologicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Servidor_Sistema_Geologia.Usuario", "UsuarioActualizacion")
                        .WithMany()
                        .HasForeignKey("UsuarioActualizacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Servidor_Sistema_Geologia.Usuario", "UsuarioCreacion")
                        .WithMany()
                        .HasForeignKey("UsuarioCreacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Servidor_Sistema_Geologia.Usuario", "UsuarioEliminacion")
                        .WithMany()
                        .HasForeignKey("UsuarioEliminacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Galeria");

                    b.Navigation("UsuarioActualizacion");

                    b.Navigation("UsuarioCreacion");

                    b.Navigation("UsuarioEliminacion");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Galeria.GaleriaElementoGeologico", b =>
                {
                    b.HasOne("Servidor_Sistema_Geologia.ElementoGeologico", "ElementoGeologico")
                        .WithOne("Galeria")
                        .HasForeignKey("Servidor_Sistema_Geologia.Galeria.GaleriaElementoGeologico", "ElementoGeologicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Servidor_Sistema_Geologia.Usuario", "UsuarioActualizacion")
                        .WithMany()
                        .HasForeignKey("UsuarioActualizacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Servidor_Sistema_Geologia.Usuario", "UsuarioCreacion")
                        .WithMany()
                        .HasForeignKey("UsuarioCreacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Servidor_Sistema_Geologia.Usuario", "UsuarioEliminacion")
                        .WithMany()
                        .HasForeignKey("UsuarioEliminacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ElementoGeologico");

                    b.Navigation("UsuarioActualizacion");

                    b.Navigation("UsuarioCreacion");

                    b.Navigation("UsuarioEliminacion");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Pais", b =>
                {
                    b.HasOne("Servidor_Sistema_Geologia.Usuario", "UsuarioActualizacion")
                        .WithMany()
                        .HasForeignKey("UsuarioActualizacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Servidor_Sistema_Geologia.Usuario", "UsuarioCreacion")
                        .WithMany()
                        .HasForeignKey("UsuarioCreacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Servidor_Sistema_Geologia.Usuario", "UsuarioEliminacion")
                        .WithMany()
                        .HasForeignKey("UsuarioEliminacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UsuarioActualizacion");

                    b.Navigation("UsuarioCreacion");

                    b.Navigation("UsuarioEliminacion");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Provincia", b =>
                {
                    b.HasOne("Servidor_Sistema_Geologia.Pais", "Pais")
                        .WithMany("Provincias")
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Servidor_Sistema_Geologia.Usuario", "UsuarioActualizacion")
                        .WithMany()
                        .HasForeignKey("UsuarioActualizacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Servidor_Sistema_Geologia.Usuario", "UsuarioCreacion")
                        .WithMany()
                        .HasForeignKey("UsuarioCreacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Servidor_Sistema_Geologia.Usuario", "UsuarioEliminacion")
                        .WithMany()
                        .HasForeignKey("UsuarioEliminacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Pais");

                    b.Navigation("UsuarioActualizacion");

                    b.Navigation("UsuarioCreacion");

                    b.Navigation("UsuarioEliminacion");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Ubicacion", b =>
                {
                    b.HasOne("Servidor_Sistema_Geologia.Pais", "Pais")
                        .WithMany()
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Servidor_Sistema_Geologia.Provincia", "Provincia")
                        .WithMany("Ubicaciones")
                        .HasForeignKey("ProvinciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Servidor_Sistema_Geologia.Usuario", "UsuarioActualizacion")
                        .WithMany()
                        .HasForeignKey("UsuarioActualizacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Servidor_Sistema_Geologia.Usuario", "UsuarioCreacion")
                        .WithMany()
                        .HasForeignKey("UsuarioCreacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Servidor_Sistema_Geologia.Usuario", "UsuarioEliminacion")
                        .WithMany()
                        .HasForeignKey("UsuarioEliminacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Pais");

                    b.Navigation("Provincia");

                    b.Navigation("UsuarioActualizacion");

                    b.Navigation("UsuarioCreacion");

                    b.Navigation("UsuarioEliminacion");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.ElementoGeologico", b =>
                {
                    b.Navigation("Galeria");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Galeria.GaleriaElementoGeologico", b =>
                {
                    b.Navigation("Fotos");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Pais", b =>
                {
                    b.Navigation("Provincias");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Provincia", b =>
                {
                    b.Navigation("Ubicaciones");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Ubicacion", b =>
                {
                    b.Navigation("ElementosGeologicos");
                });
#pragma warning restore 612, 618
        }
    }
}
