// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Servidor_Sistema_Geologia.DAL;

#nullable disable

namespace Servidor_Sistema_Geologia.Migrations
{
    [DbContext(typeof(GestorSistemaGeologia))]
    partial class GestorGeologiaModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Models.Acceso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Accion")
                        .HasColumnType("int");

                    b.Property<int?>("ElementoGeologicoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAcceso")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioId1")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ElementoGeologicoId");

                    b.HasIndex("UsuarioId1");

                    b.ToTable("Accesos");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Models.ElementoGeologico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("DocumentosRelacionados")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Donante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Edad")
                        .HasColumnType("int");

                    b.Property<int?>("Ejemplares")
                        .HasColumnType("int");

                    b.Property<int?>("EstadoElementoId")
                        .HasColumnType("int");

                    b.Property<int>("FechaIngreso")
                        .HasColumnType("int");

                    b.Property<bool?>("LaminaExiste")
                        .HasColumnType("bit");

                    b.Property<string>("LaminaURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UbicacionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstadoElementoId");

                    b.HasIndex("UbicacionId");

                    b.ToTable("ElementosGeologicos");

                    b.HasDiscriminator().HasValue("ElementoGeologico");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Models.EstadoElemento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DescripcionEstado")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EstadosElementos");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Models.FotoElemento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreadoPor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescripcionEspecifica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ElementoGeologicoId")
                        .HasColumnType("int");

                    b.Property<string>("Etiquetas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaSubida")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GaleriaElementosGeologicoId")
                        .HasColumnType("int");

                    b.Property<int?>("GaleriaId")
                        .HasColumnType("int");

                    b.Property<byte[]>("Imagen")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("TipoFoto")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ElementoGeologicoId");

                    b.HasIndex("GaleriaId");

                    b.ToTable("FotosElementos");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Models.GaleriaElementoGeologico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DetalleGrupo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ElementoGeologicoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ElementoGeologicoId");

                    b.ToTable("GaleriaElementosGeologicos");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Models.Pais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NombrePais")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Paises");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Models.Provincia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreProvincia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PaisId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaisId");

                    b.ToTable("Provincias");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Models.Ubicacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Latitud")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Leyenda")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Localidad")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Longitud")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int?>("PaisId")
                        .HasColumnType("int");

                    b.Property<int?>("ProvinciaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaisId");

                    b.HasIndex("ProvinciaId");

                    b.ToTable("Ubicaciones");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Models.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Apellidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nombres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Models.Fosil", b =>
                {
                    b.HasBaseType("Servidor_Sistema_Geologia.Models.ElementoGeologico");

                    b.Property<string>("Especie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Periodo")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Fosil");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Models.Roca", b =>
                {
                    b.HasBaseType("Servidor_Sistema_Geologia.Models.ElementoGeologico");

                    b.Property<string>("Litologia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoRoca")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Roca");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Servidor_Sistema_Geologia.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Servidor_Sistema_Geologia.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Servidor_Sistema_Geologia.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Servidor_Sistema_Geologia.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Models.Acceso", b =>
                {
                    b.HasOne("Servidor_Sistema_Geologia.Models.ElementoGeologico", "ElementoGeologico")
                        .WithMany()
                        .HasForeignKey("ElementoGeologicoId");

                    b.HasOne("Servidor_Sistema_Geologia.Models.Usuario", "Usuario")
                        .WithMany("Accesos")
                        .HasForeignKey("UsuarioId1");

                    b.Navigation("ElementoGeologico");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Models.ElementoGeologico", b =>
                {
                    b.HasOne("Servidor_Sistema_Geologia.Models.EstadoElemento", "EstadoElemento")
                        .WithMany()
                        .HasForeignKey("EstadoElementoId");

                    b.HasOne("Servidor_Sistema_Geologia.Models.Ubicacion", "Ubicacion")
                        .WithMany("ElementosGeologicos")
                        .HasForeignKey("UbicacionId");

                    b.Navigation("EstadoElemento");

                    b.Navigation("Ubicacion");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Models.FotoElemento", b =>
                {
                    b.HasOne("Servidor_Sistema_Geologia.Models.ElementoGeologico", "ElementoGeologico")
                        .WithMany("Fotos")
                        .HasForeignKey("ElementoGeologicoId");

                    b.HasOne("Servidor_Sistema_Geologia.Models.GaleriaElementoGeologico", "Galeria")
                        .WithMany("Fotos")
                        .HasForeignKey("GaleriaId");

                    b.Navigation("ElementoGeologico");

                    b.Navigation("Galeria");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Models.GaleriaElementoGeologico", b =>
                {
                    b.HasOne("Servidor_Sistema_Geologia.Models.ElementoGeologico", "ElementoGeologico")
                        .WithMany()
                        .HasForeignKey("ElementoGeologicoId");

                    b.Navigation("ElementoGeologico");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Models.Provincia", b =>
                {
                    b.HasOne("Servidor_Sistema_Geologia.Models.Pais", "Pais")
                        .WithMany("Provincias")
                        .HasForeignKey("PaisId");

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Models.Ubicacion", b =>
                {
                    b.HasOne("Servidor_Sistema_Geologia.Models.Pais", "Pais")
                        .WithMany()
                        .HasForeignKey("PaisId");

                    b.HasOne("Servidor_Sistema_Geologia.Models.Provincia", "Provincia")
                        .WithMany("Ubicaciones")
                        .HasForeignKey("ProvinciaId");

                    b.Navigation("Pais");

                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Models.ElementoGeologico", b =>
                {
                    b.Navigation("Fotos");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Models.GaleriaElementoGeologico", b =>
                {
                    b.Navigation("Fotos");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Models.Pais", b =>
                {
                    b.Navigation("Provincias");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Models.Provincia", b =>
                {
                    b.Navigation("Ubicaciones");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Models.Ubicacion", b =>
                {
                    b.Navigation("ElementosGeologicos");
                });

            modelBuilder.Entity("Servidor_Sistema_Geologia.Models.Usuario", b =>
                {
                    b.Navigation("Accesos");
                });
#pragma warning restore 612, 618
        }
    }
}
